### ISSUE TITLE
RE: http://nebarnix.com/img2gco/

### ISSUE THREAD

**Issue by simonwaw** [nebarnix/Project-Desert-Tortoise#8]
Hi,

Just trying to reach you regarding your project at: http://nebarnix.com/img2gco/ - unfortunately you don't have any contact details on your website.

Any chance you could put the source for this project up on github?

I'm getting excellent results but would love to tweak some stuff to get faster 'print' speeds when doing simple black and white graphics with mostly white non-burned areas.

Look forward to hearing from you.

**Comment by nebarnix** [comment]
oh hey :)

yeah I can do that! Give me a minute or 1440.

I am glad that people are finding this tool useful!

On Mon, Jun 13, 2016 at 10:35 AM, simonwaw notifications@github.com wrote:

> Hi,
> 
> Just trying to reach you regarding your project at:
> http://nebarnix.com/img2gco/ - unfortunately you don't have any contact
> details on your website.
> 
> Any chance you could put the source for this project up on github?
> 
> I'm getting excellent results but would love to tweak some stuff to get
> faster 'print' speeds when doing simple black and white graphics with
> mostly white non-burned areas.
> 
> Look forward to hearing from you.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/nebarnix/Project-Desert-Tortoise/issues/8, or mute
> the thread
> https://github.com/notifications/unsubscribe/AAnQxCSpIz1782xNga3Hpt87zHcqOovQks5qLZTjgaJpZM4I0j87
> .

## 

---

Jasper Nance - KE7PHI
Creative and Scientific Imagery
http://www.nebarnix.com/

**Comment by simonwaw** [comment]
Awesome!  Yeah it's quite basic looking from a UI perspective but the end results (gcode output) are amazing! The resolution/quality of the "print" are fantastic :)  

Looking forward to tweaking for my needs :)

Thanks!

**Comment by nebarnix** [comment]
Posted!

https://github.com/nebarnix/img2gco/

On Mon, Jun 13, 2016 at 7:15 PM, Jasper Nance nebarotype@gmail.com wrote:

> oh hey :)
> 
> yeah I can do that! Give me a minute or 1440.
> 
> I am glad that people are finding this tool useful!
> 
> On Mon, Jun 13, 2016 at 10:35 AM, simonwaw notifications@github.com
> wrote:
> 
> > Hi,
> > 
> > Just trying to reach you regarding your project at:
> > http://nebarnix.com/img2gco/ - unfortunately you don't have any contact
> > details on your website.
> > 
> > Any chance you could put the source for this project up on github?
> > 
> > I'm getting excellent results but would love to tweak some stuff to get
> > faster 'print' speeds when doing simple black and white graphics with
> > mostly white non-burned areas.
> > 
> > Look forward to hearing from you.
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > https://github.com/nebarnix/Project-Desert-Tortoise/issues/8, or mute
> > the thread
> > https://github.com/notifications/unsubscribe/AAnQxCSpIz1782xNga3Hpt87zHcqOovQks5qLZTjgaJpZM4I0j87
> > .
> 
> ## 
> 
> ---
> 
> Jasper Nance - KE7PHI
> Creative and Scientific Imagery
> http://www.nebarnix.com/

## 

---

Jasper Nance - KE7PHI
Creative and Scientific Imagery
http://www.nebarnix.com/

**Comment by malakada** [comment]
Make sure to send PRs for your tweaks!

**Comment by nebarnix** [comment]
What's a PR?

**Comment by systmdamage** [comment]
First, Thank you so much for this and adding it to github!  This has been such a huge help!  With that being said, is there anyway you could add a bounding box (skirt) option to it so we can make sure the object we are engraving centered correctly?  Like if i'm engraving a 5x7 image, just burn a 5x7 box where the image would go...then pause for user interaction before the rest of the burn starts...Thanks in advance, this works great!  And I really appreciate all your work!
